// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;

import 'utils/local_storage/entity/outlet_entity.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
      id: const obx_int.IdUid(1, 2599891849544336321),
      name: 'LocalOutlet',
      lastPropertyId: const obx_int.IdUid(11, 4328767069488482538),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 1376805503561498808),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 3002375310847627291),
            name: 'userId',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 4425978140995024838),
            name: 'nameOutlet',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 3974127522533181519),
            name: 'latitude',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 6137864039725494204),
            name: 'longitude',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(6, 2994755807437625910),
            name: 'address',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(7, 2853414636912836578),
            name: 'imageUrl',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(8, 8251792396267962807),
            name: 'clockIn',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(9, 7845370802278231778),
            name: 'clockOut',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(10, 5141847415843083919),
            name: 'userLatitude',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(11, 4328767069488482538),
            name: 'userLongitude',
            type: 9,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[])
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
obx.Store openStore(
    {String? directory,
    int? maxDBSizeInKB,
    int? maxDataSizeInKB,
    int? fileMode,
    int? maxReaders,
    bool queriesCaseSensitiveDefault = true,
    String? macosApplicationGroup}) {
  return obx.Store(getObjectBoxModel(),
      directory: directory,
      maxDBSizeInKB: maxDBSizeInKB,
      maxDataSizeInKB: maxDataSizeInKB,
      fileMode: fileMode,
      maxReaders: maxReaders,
      queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
      macosApplicationGroup: macosApplicationGroup);
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
      entities: _entities,
      lastEntityId: const obx_int.IdUid(1, 2599891849544336321),
      lastIndexId: const obx_int.IdUid(0, 0),
      lastRelationId: const obx_int.IdUid(0, 0),
      lastSequenceId: const obx_int.IdUid(0, 0),
      retiredEntityUids: const [],
      retiredIndexUids: const [],
      retiredPropertyUids: const [],
      retiredRelationUids: const [],
      modelVersion: 5,
      modelVersionParserMinimum: 5,
      version: 1);

  final bindings = <Type, obx_int.EntityDefinition>{
    LocalOutlet: obx_int.EntityDefinition<LocalOutlet>(
        model: _entities[0],
        toOneRelations: (LocalOutlet object) => [],
        toManyRelations: (LocalOutlet object) => {},
        getId: (LocalOutlet object) => object.id,
        setId: (LocalOutlet object, int id) {
          object.id = id;
        },
        objectToFB: (LocalOutlet object, fb.Builder fbb) {
          final nameOutletOffset = object.nameOutlet == null
              ? null
              : fbb.writeString(object.nameOutlet!);
          final latitudeOffset = object.latitude == null
              ? null
              : fbb.writeString(object.latitude!);
          final longitudeOffset = object.longitude == null
              ? null
              : fbb.writeString(object.longitude!);
          final addressOffset =
              object.address == null ? null : fbb.writeString(object.address!);
          final imageUrlOffset = object.imageUrl == null
              ? null
              : fbb.writeString(object.imageUrl!);
          final clockInOffset =
              object.clockIn == null ? null : fbb.writeString(object.clockIn!);
          final clockOutOffset = object.clockOut == null
              ? null
              : fbb.writeString(object.clockOut!);
          final userLatitudeOffset = object.userLatitude == null
              ? null
              : fbb.writeString(object.userLatitude!);
          final userLongitudeOffset = object.userLongitude == null
              ? null
              : fbb.writeString(object.userLongitude!);
          fbb.startTable(12);
          fbb.addInt64(0, object.id ?? 0);
          fbb.addInt64(1, object.userId);
          fbb.addOffset(2, nameOutletOffset);
          fbb.addOffset(3, latitudeOffset);
          fbb.addOffset(4, longitudeOffset);
          fbb.addOffset(5, addressOffset);
          fbb.addOffset(6, imageUrlOffset);
          fbb.addOffset(7, clockInOffset);
          fbb.addOffset(8, clockOutOffset);
          fbb.addOffset(9, userLatitudeOffset);
          fbb.addOffset(10, userLongitudeOffset);
          fbb.finish(fbb.endTable());
          return object.id ?? 0;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final idParam =
              const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 4);
          final userIdParam =
              const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 6);
          final nameOutletParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 8);
          final latitudeParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 10);
          final longitudeParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 12);
          final addressParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 14);
          final imageUrlParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 16);
          final clockInParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 18);
          final clockOutParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 20);
          final userLatitudeParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 22);
          final userLongitudeParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 24);
          final object = LocalOutlet(
              id: idParam,
              userId: userIdParam,
              nameOutlet: nameOutletParam,
              latitude: latitudeParam,
              longitude: longitudeParam,
              address: addressParam,
              imageUrl: imageUrlParam,
              clockIn: clockInParam,
              clockOut: clockOutParam,
              userLatitude: userLatitudeParam,
              userLongitude: userLongitudeParam);

          return object;
        })
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [LocalOutlet] entity fields to define ObjectBox queries.
class LocalOutlet_ {
  /// See [LocalOutlet.id].
  static final id =
      obx.QueryIntegerProperty<LocalOutlet>(_entities[0].properties[0]);

  /// See [LocalOutlet.userId].
  static final userId =
      obx.QueryIntegerProperty<LocalOutlet>(_entities[0].properties[1]);

  /// See [LocalOutlet.nameOutlet].
  static final nameOutlet =
      obx.QueryStringProperty<LocalOutlet>(_entities[0].properties[2]);

  /// See [LocalOutlet.latitude].
  static final latitude =
      obx.QueryStringProperty<LocalOutlet>(_entities[0].properties[3]);

  /// See [LocalOutlet.longitude].
  static final longitude =
      obx.QueryStringProperty<LocalOutlet>(_entities[0].properties[4]);

  /// See [LocalOutlet.address].
  static final address =
      obx.QueryStringProperty<LocalOutlet>(_entities[0].properties[5]);

  /// See [LocalOutlet.imageUrl].
  static final imageUrl =
      obx.QueryStringProperty<LocalOutlet>(_entities[0].properties[6]);

  /// See [LocalOutlet.clockIn].
  static final clockIn =
      obx.QueryStringProperty<LocalOutlet>(_entities[0].properties[7]);

  /// See [LocalOutlet.clockOut].
  static final clockOut =
      obx.QueryStringProperty<LocalOutlet>(_entities[0].properties[8]);

  /// See [LocalOutlet.userLatitude].
  static final userLatitude =
      obx.QueryStringProperty<LocalOutlet>(_entities[0].properties[9]);

  /// See [LocalOutlet.userLongitude].
  static final userLongitude =
      obx.QueryStringProperty<LocalOutlet>(_entities[0].properties[10]);
}
